name: generate snake contribution graph

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the Snake SVG to the output branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B output
          mv dist/github-contribution-grid-snake.svg output/github-contribution-grid-snake.svg
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generate and push snake SVG"
          git push -f origin output
